### PR TITLE
Add sample class

### LINKED ISSUE #81: Add sample class
The need for a `Sample` class emerges when multiple samples are cut from a bulk material, each treated as a separate entity. These samples have the same material system but can have different geometry and sample IDs assigned.

The `Sample` class should allow the reuse of a material system (a composite system itself) for multiple sample entries via reference. 

`Sample` also inherits composite system, and reference to its material system is made in the `components` using a `SystemComponent`.
```py
Sample(CompositeSystem):
  geometry = Geometry
  components = list[SystemComponent(reference=CompositeSystem)]
```

### PR DESCRIPTION
**Pull request by ka-sarthak**
Resolves #81

### CODE REVIEW

**Review by hampusnasstrom — COMMENTED** [review]
Sample is a very loaded name and from *very* long discussions from before you came, I think we decided that sample is a role. This would be something we should definitely discuss with the whole A team before moving forward on.

**Comment by aalbino2** [comment]
I believe we can skip this intermediate class, let's simply add "geometry" subsection whereever is needed, like we have in substrate, without the need of this semi-general step

What do you think?

**Review by aalbino2 — COMMENTED** [review]
which is the sample that undergoes a cut and needs geometry specifications here?

**Comment by ka-sarthak** [comment]
@aalbino2 @hampusnasstrom I see. Based on our discussions in today's team meet:
- getting a consensus on the term `Sample` will mean more discussions beyond this PR, which have already occurred in recent years. 
- `CompositeSystem` is meant to handle samples. A possibility could be to add geometry in the `CompositeSystem`. However, since geometry is optional for the composite system, it should be added while extending `CompositeSystem`.
- In coming months, `System` will replace CompositeSystem, making these classes even more general. Adding geometry there is not recommended.
- Suggestion: move this class to the IKZ plugin. And the name of the class will be `<Synthesis process name>IKZSample`.

**Pull request closed without merging**
